// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/carbonable/carbonable-portfolio-backend/ent/customertokens"
	"github.com/carbonable/carbonable-portfolio-backend/ent/predicate"
	"github.com/carbonable/carbonable-portfolio-backend/ent/project"
)

// CustomerTokensQuery is the builder for querying CustomerTokens entities.
type CustomerTokensQuery struct {
	config
	ctx              *QueryContext
	order            []customertokens.OrderOption
	inters           []Interceptor
	predicates       []predicate.CustomerTokens
	withProject      *ProjectQuery
	modifiers        []func(*sql.Selector)
	loadTotal        []func(context.Context, []*CustomerTokens) error
	withNamedProject map[string]*ProjectQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CustomerTokensQuery builder.
func (ctq *CustomerTokensQuery) Where(ps ...predicate.CustomerTokens) *CustomerTokensQuery {
	ctq.predicates = append(ctq.predicates, ps...)
	return ctq
}

// Limit the number of records to be returned by this query.
func (ctq *CustomerTokensQuery) Limit(limit int) *CustomerTokensQuery {
	ctq.ctx.Limit = &limit
	return ctq
}

// Offset to start from.
func (ctq *CustomerTokensQuery) Offset(offset int) *CustomerTokensQuery {
	ctq.ctx.Offset = &offset
	return ctq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ctq *CustomerTokensQuery) Unique(unique bool) *CustomerTokensQuery {
	ctq.ctx.Unique = &unique
	return ctq
}

// Order specifies how the records should be ordered.
func (ctq *CustomerTokensQuery) Order(o ...customertokens.OrderOption) *CustomerTokensQuery {
	ctq.order = append(ctq.order, o...)
	return ctq
}

// QueryProject chains the current query on the "project" edge.
func (ctq *CustomerTokensQuery) QueryProject() *ProjectQuery {
	query := (&ProjectClient{config: ctq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ctq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ctq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(customertokens.Table, customertokens.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, customertokens.ProjectTable, customertokens.ProjectPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(ctq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CustomerTokens entity from the query.
// Returns a *NotFoundError when no CustomerTokens was found.
func (ctq *CustomerTokensQuery) First(ctx context.Context) (*CustomerTokens, error) {
	nodes, err := ctq.Limit(1).All(setContextOp(ctx, ctq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{customertokens.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ctq *CustomerTokensQuery) FirstX(ctx context.Context) *CustomerTokens {
	node, err := ctq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CustomerTokens ID from the query.
// Returns a *NotFoundError when no CustomerTokens ID was found.
func (ctq *CustomerTokensQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ctq.Limit(1).IDs(setContextOp(ctx, ctq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{customertokens.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ctq *CustomerTokensQuery) FirstIDX(ctx context.Context) int {
	id, err := ctq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CustomerTokens entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CustomerTokens entity is found.
// Returns a *NotFoundError when no CustomerTokens entities are found.
func (ctq *CustomerTokensQuery) Only(ctx context.Context) (*CustomerTokens, error) {
	nodes, err := ctq.Limit(2).All(setContextOp(ctx, ctq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{customertokens.Label}
	default:
		return nil, &NotSingularError{customertokens.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ctq *CustomerTokensQuery) OnlyX(ctx context.Context) *CustomerTokens {
	node, err := ctq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CustomerTokens ID in the query.
// Returns a *NotSingularError when more than one CustomerTokens ID is found.
// Returns a *NotFoundError when no entities are found.
func (ctq *CustomerTokensQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ctq.Limit(2).IDs(setContextOp(ctx, ctq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{customertokens.Label}
	default:
		err = &NotSingularError{customertokens.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ctq *CustomerTokensQuery) OnlyIDX(ctx context.Context) int {
	id, err := ctq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CustomerTokensSlice.
func (ctq *CustomerTokensQuery) All(ctx context.Context) ([]*CustomerTokens, error) {
	ctx = setContextOp(ctx, ctq.ctx, "All")
	if err := ctq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CustomerTokens, *CustomerTokensQuery]()
	return withInterceptors[[]*CustomerTokens](ctx, ctq, qr, ctq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ctq *CustomerTokensQuery) AllX(ctx context.Context) []*CustomerTokens {
	nodes, err := ctq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CustomerTokens IDs.
func (ctq *CustomerTokensQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ctq.ctx.Unique == nil && ctq.path != nil {
		ctq.Unique(true)
	}
	ctx = setContextOp(ctx, ctq.ctx, "IDs")
	if err = ctq.Select(customertokens.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ctq *CustomerTokensQuery) IDsX(ctx context.Context) []int {
	ids, err := ctq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ctq *CustomerTokensQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ctq.ctx, "Count")
	if err := ctq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ctq, querierCount[*CustomerTokensQuery](), ctq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ctq *CustomerTokensQuery) CountX(ctx context.Context) int {
	count, err := ctq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ctq *CustomerTokensQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ctq.ctx, "Exist")
	switch _, err := ctq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ctq *CustomerTokensQuery) ExistX(ctx context.Context) bool {
	exist, err := ctq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CustomerTokensQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ctq *CustomerTokensQuery) Clone() *CustomerTokensQuery {
	if ctq == nil {
		return nil
	}
	return &CustomerTokensQuery{
		config:      ctq.config,
		ctx:         ctq.ctx.Clone(),
		order:       append([]customertokens.OrderOption{}, ctq.order...),
		inters:      append([]Interceptor{}, ctq.inters...),
		predicates:  append([]predicate.CustomerTokens{}, ctq.predicates...),
		withProject: ctq.withProject.Clone(),
		// clone intermediate query.
		sql:  ctq.sql.Clone(),
		path: ctq.path,
	}
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (ctq *CustomerTokensQuery) WithProject(opts ...func(*ProjectQuery)) *CustomerTokensQuery {
	query := (&ProjectClient{config: ctq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ctq.withProject = query
	return ctq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Address string `json:"address,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CustomerTokens.Query().
//		GroupBy(customertokens.FieldAddress).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ctq *CustomerTokensQuery) GroupBy(field string, fields ...string) *CustomerTokensGroupBy {
	ctq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CustomerTokensGroupBy{build: ctq}
	grbuild.flds = &ctq.ctx.Fields
	grbuild.label = customertokens.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Address string `json:"address,omitempty"`
//	}
//
//	client.CustomerTokens.Query().
//		Select(customertokens.FieldAddress).
//		Scan(ctx, &v)
func (ctq *CustomerTokensQuery) Select(fields ...string) *CustomerTokensSelect {
	ctq.ctx.Fields = append(ctq.ctx.Fields, fields...)
	sbuild := &CustomerTokensSelect{CustomerTokensQuery: ctq}
	sbuild.label = customertokens.Label
	sbuild.flds, sbuild.scan = &ctq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CustomerTokensSelect configured with the given aggregations.
func (ctq *CustomerTokensQuery) Aggregate(fns ...AggregateFunc) *CustomerTokensSelect {
	return ctq.Select().Aggregate(fns...)
}

func (ctq *CustomerTokensQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ctq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ctq); err != nil {
				return err
			}
		}
	}
	for _, f := range ctq.ctx.Fields {
		if !customertokens.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ctq.path != nil {
		prev, err := ctq.path(ctx)
		if err != nil {
			return err
		}
		ctq.sql = prev
	}
	return nil
}

func (ctq *CustomerTokensQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CustomerTokens, error) {
	var (
		nodes       = []*CustomerTokens{}
		_spec       = ctq.querySpec()
		loadedTypes = [1]bool{
			ctq.withProject != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CustomerTokens).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CustomerTokens{config: ctq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(ctq.modifiers) > 0 {
		_spec.Modifiers = ctq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ctq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ctq.withProject; query != nil {
		if err := ctq.loadProject(ctx, query, nodes,
			func(n *CustomerTokens) { n.Edges.Project = []*Project{} },
			func(n *CustomerTokens, e *Project) { n.Edges.Project = append(n.Edges.Project, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range ctq.withNamedProject {
		if err := ctq.loadProject(ctx, query, nodes,
			func(n *CustomerTokens) { n.appendNamedProject(name) },
			func(n *CustomerTokens, e *Project) { n.appendNamedProject(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range ctq.loadTotal {
		if err := ctq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ctq *CustomerTokensQuery) loadProject(ctx context.Context, query *ProjectQuery, nodes []*CustomerTokens, init func(*CustomerTokens), assign func(*CustomerTokens, *Project)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*CustomerTokens)
	nids := make(map[int]map[*CustomerTokens]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(customertokens.ProjectTable)
		s.Join(joinT).On(s.C(project.FieldID), joinT.C(customertokens.ProjectPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(customertokens.ProjectPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(customertokens.ProjectPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*CustomerTokens]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Project](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "project" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (ctq *CustomerTokensQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ctq.querySpec()
	if len(ctq.modifiers) > 0 {
		_spec.Modifiers = ctq.modifiers
	}
	_spec.Node.Columns = ctq.ctx.Fields
	if len(ctq.ctx.Fields) > 0 {
		_spec.Unique = ctq.ctx.Unique != nil && *ctq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ctq.driver, _spec)
}

func (ctq *CustomerTokensQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(customertokens.Table, customertokens.Columns, sqlgraph.NewFieldSpec(customertokens.FieldID, field.TypeInt))
	_spec.From = ctq.sql
	if unique := ctq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ctq.path != nil {
		_spec.Unique = true
	}
	if fields := ctq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, customertokens.FieldID)
		for i := range fields {
			if fields[i] != customertokens.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ctq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ctq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ctq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ctq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ctq *CustomerTokensQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ctq.driver.Dialect())
	t1 := builder.Table(customertokens.Table)
	columns := ctq.ctx.Fields
	if len(columns) == 0 {
		columns = customertokens.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ctq.sql != nil {
		selector = ctq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ctq.ctx.Unique != nil && *ctq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ctq.predicates {
		p(selector)
	}
	for _, p := range ctq.order {
		p(selector)
	}
	if offset := ctq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ctq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedProject tells the query-builder to eager-load the nodes that are connected to the "project"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (ctq *CustomerTokensQuery) WithNamedProject(name string, opts ...func(*ProjectQuery)) *CustomerTokensQuery {
	query := (&ProjectClient{config: ctq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if ctq.withNamedProject == nil {
		ctq.withNamedProject = make(map[string]*ProjectQuery)
	}
	ctq.withNamedProject[name] = query
	return ctq
}

// CustomerTokensGroupBy is the group-by builder for CustomerTokens entities.
type CustomerTokensGroupBy struct {
	selector
	build *CustomerTokensQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ctgb *CustomerTokensGroupBy) Aggregate(fns ...AggregateFunc) *CustomerTokensGroupBy {
	ctgb.fns = append(ctgb.fns, fns...)
	return ctgb
}

// Scan applies the selector query and scans the result into the given value.
func (ctgb *CustomerTokensGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ctgb.build.ctx, "GroupBy")
	if err := ctgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CustomerTokensQuery, *CustomerTokensGroupBy](ctx, ctgb.build, ctgb, ctgb.build.inters, v)
}

func (ctgb *CustomerTokensGroupBy) sqlScan(ctx context.Context, root *CustomerTokensQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ctgb.fns))
	for _, fn := range ctgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ctgb.flds)+len(ctgb.fns))
		for _, f := range *ctgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ctgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ctgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CustomerTokensSelect is the builder for selecting fields of CustomerTokens entities.
type CustomerTokensSelect struct {
	*CustomerTokensQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cts *CustomerTokensSelect) Aggregate(fns ...AggregateFunc) *CustomerTokensSelect {
	cts.fns = append(cts.fns, fns...)
	return cts
}

// Scan applies the selector query and scans the result into the given value.
func (cts *CustomerTokensSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cts.ctx, "Select")
	if err := cts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CustomerTokensQuery, *CustomerTokensSelect](ctx, cts.CustomerTokensQuery, cts, cts.inters, v)
}

func (cts *CustomerTokensSelect) sqlScan(ctx context.Context, root *CustomerTokensQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cts.fns))
	for _, fn := range cts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
