// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/carbonable/carbonable-portfolio-backend/ent/customertokens"
	"github.com/carbonable/carbonable-portfolio-backend/ent/project"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (ct *CustomerTokensQuery) CollectFields(ctx context.Context, satisfies ...string) (*CustomerTokensQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return ct, nil
	}
	if err := ct.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return ct, nil
}

func (ct *CustomerTokensQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(customertokens.Columns))
		selectedFields = []string{customertokens.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "project":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ProjectClient{config: ct.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, projectImplementors)...); err != nil {
				return err
			}
			ct.WithNamedProject(alias, func(wq *ProjectQuery) {
				*wq = *query
			})
		case "address":
			if _, ok := fieldSeen[customertokens.FieldAddress]; !ok {
				selectedFields = append(selectedFields, customertokens.FieldAddress)
				fieldSeen[customertokens.FieldAddress] = struct{}{}
			}
		case "projectAddress":
			if _, ok := fieldSeen[customertokens.FieldProjectAddress]; !ok {
				selectedFields = append(selectedFields, customertokens.FieldProjectAddress)
				fieldSeen[customertokens.FieldProjectAddress] = struct{}{}
			}
		case "slot":
			if _, ok := fieldSeen[customertokens.FieldSlot]; !ok {
				selectedFields = append(selectedFields, customertokens.FieldSlot)
				fieldSeen[customertokens.FieldSlot] = struct{}{}
			}
		case "tokenID":
			if _, ok := fieldSeen[customertokens.FieldTokenID]; !ok {
				selectedFields = append(selectedFields, customertokens.FieldTokenID)
				fieldSeen[customertokens.FieldTokenID] = struct{}{}
			}
		case "value":
			if _, ok := fieldSeen[customertokens.FieldValue]; !ok {
				selectedFields = append(selectedFields, customertokens.FieldValue)
				fieldSeen[customertokens.FieldValue] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		ct.Select(selectedFields...)
	}
	return nil
}

type customertokensPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []CustomerTokensPaginateOption
}

func newCustomerTokensPaginateArgs(rv map[string]any) *customertokensPaginateArgs {
	args := &customertokensPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*CustomerTokensWhereInput); ok {
		args.opts = append(args.opts, WithCustomerTokensFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (pr *ProjectQuery) CollectFields(ctx context.Context, satisfies ...string) (*ProjectQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return pr, nil
	}
	if err := pr.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return pr, nil
}

func (pr *ProjectQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(project.Columns))
		selectedFields = []string{project.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "tokens":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&CustomerTokensClient{config: pr.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, customertokensImplementors)...); err != nil {
				return err
			}
			pr.WithNamedTokens(alias, func(wq *CustomerTokensQuery) {
				*wq = *query
			})
		case "address":
			if _, ok := fieldSeen[project.FieldAddress]; !ok {
				selectedFields = append(selectedFields, project.FieldAddress)
				fieldSeen[project.FieldAddress] = struct{}{}
			}
		case "slot":
			if _, ok := fieldSeen[project.FieldSlot]; !ok {
				selectedFields = append(selectedFields, project.FieldSlot)
				fieldSeen[project.FieldSlot] = struct{}{}
			}
		case "minterAddress":
			if _, ok := fieldSeen[project.FieldMinterAddress]; !ok {
				selectedFields = append(selectedFields, project.FieldMinterAddress)
				fieldSeen[project.FieldMinterAddress] = struct{}{}
			}
		case "name":
			if _, ok := fieldSeen[project.FieldName]; !ok {
				selectedFields = append(selectedFields, project.FieldName)
				fieldSeen[project.FieldName] = struct{}{}
			}
		case "abi":
			if _, ok := fieldSeen[project.FieldAbi]; !ok {
				selectedFields = append(selectedFields, project.FieldAbi)
				fieldSeen[project.FieldAbi] = struct{}{}
			}
		case "image":
			if _, ok := fieldSeen[project.FieldImage]; !ok {
				selectedFields = append(selectedFields, project.FieldImage)
				fieldSeen[project.FieldImage] = struct{}{}
			}
		case "yielderAddress":
			if _, ok := fieldSeen[project.FieldYielderAddress]; !ok {
				selectedFields = append(selectedFields, project.FieldYielderAddress)
				fieldSeen[project.FieldYielderAddress] = struct{}{}
			}
		case "offseterAddress":
			if _, ok := fieldSeen[project.FieldOffseterAddress]; !ok {
				selectedFields = append(selectedFields, project.FieldOffseterAddress)
				fieldSeen[project.FieldOffseterAddress] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		pr.Select(selectedFields...)
	}
	return nil
}

type projectPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []ProjectPaginateOption
}

func newProjectPaginateArgs(rv map[string]any) *projectPaginateArgs {
	args := &projectPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*ProjectWhereInput); ok {
		args.opts = append(args.opts, WithProjectFilter(v.Filter))
	}
	return args
}

const (
	afterField     = "after"
	firstField     = "first"
	beforeField    = "before"
	lastField      = "last"
	orderByField   = "orderBy"
	directionField = "direction"
	fieldField     = "field"
	whereField     = "where"
)

func fieldArgs(ctx context.Context, whereInput any, path ...string) map[string]any {
	field := collectedField(ctx, path...)
	if field == nil || field.Arguments == nil {
		return nil
	}
	oc := graphql.GetOperationContext(ctx)
	args := field.ArgumentMap(oc.Variables)
	return unmarshalArgs(ctx, whereInput, args)
}

// unmarshalArgs allows extracting the field arguments from their raw representation.
func unmarshalArgs(ctx context.Context, whereInput any, args map[string]any) map[string]any {
	for _, k := range []string{firstField, lastField} {
		v, ok := args[k]
		if !ok {
			continue
		}
		i, err := graphql.UnmarshalInt(v)
		if err == nil {
			args[k] = &i
		}
	}
	for _, k := range []string{beforeField, afterField} {
		v, ok := args[k]
		if !ok {
			continue
		}
		c := &Cursor{}
		if c.UnmarshalGQL(v) == nil {
			args[k] = c
		}
	}
	if v, ok := args[whereField]; ok && whereInput != nil {
		if err := graphql.UnmarshalInputFromContext(ctx, v, whereInput); err == nil {
			args[whereField] = whereInput
		}
	}

	return args
}

// mayAddCondition appends another type condition to the satisfies list
// if it does not exist in the list.
func mayAddCondition(satisfies []string, typeCond []string) []string {
Cond:
	for _, c := range typeCond {
		for _, s := range satisfies {
			if c == s {
				continue Cond
			}
		}
		satisfies = append(satisfies, c)
	}
	return satisfies
}
