// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (ct *CustomerTokens) Project(ctx context.Context) (result []*Project, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = ct.NamedProject(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = ct.Edges.ProjectOrErr()
	}
	if IsNotLoaded(err) {
		result, err = ct.QueryProject().All(ctx)
	}
	return result, err
}

func (pr *Project) Tokens(ctx context.Context) (result []*CustomerTokens, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = pr.NamedTokens(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = pr.Edges.TokensOrErr()
	}
	if IsNotLoaded(err) {
		result, err = pr.QueryTokens().All(ctx)
	}
	return result, err
}
