// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/carbonable/carbonable-portfolio-backend/ent/customertokens"
	"github.com/carbonable/carbonable-portfolio-backend/ent/project"
)

// ProjectCreate is the builder for creating a Project entity.
type ProjectCreate struct {
	config
	mutation *ProjectMutation
	hooks    []Hook
}

// SetAddress sets the "address" field.
func (pc *ProjectCreate) SetAddress(s string) *ProjectCreate {
	pc.mutation.SetAddress(s)
	return pc
}

// SetSlot sets the "slot" field.
func (pc *ProjectCreate) SetSlot(i int) *ProjectCreate {
	pc.mutation.SetSlot(i)
	return pc
}

// SetMinterAddress sets the "minter_address" field.
func (pc *ProjectCreate) SetMinterAddress(s string) *ProjectCreate {
	pc.mutation.SetMinterAddress(s)
	return pc
}

// SetName sets the "name" field.
func (pc *ProjectCreate) SetName(s string) *ProjectCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetAbi sets the "abi" field.
func (pc *ProjectCreate) SetAbi(jm json.RawMessage) *ProjectCreate {
	pc.mutation.SetAbi(jm)
	return pc
}

// SetImage sets the "image" field.
func (pc *ProjectCreate) SetImage(s string) *ProjectCreate {
	pc.mutation.SetImage(s)
	return pc
}

// SetYielderAddress sets the "yielder_address" field.
func (pc *ProjectCreate) SetYielderAddress(s string) *ProjectCreate {
	pc.mutation.SetYielderAddress(s)
	return pc
}

// SetNillableYielderAddress sets the "yielder_address" field if the given value is not nil.
func (pc *ProjectCreate) SetNillableYielderAddress(s *string) *ProjectCreate {
	if s != nil {
		pc.SetYielderAddress(*s)
	}
	return pc
}

// SetOffseterAddress sets the "offseter_address" field.
func (pc *ProjectCreate) SetOffseterAddress(s string) *ProjectCreate {
	pc.mutation.SetOffseterAddress(s)
	return pc
}

// SetNillableOffseterAddress sets the "offseter_address" field if the given value is not nil.
func (pc *ProjectCreate) SetNillableOffseterAddress(s *string) *ProjectCreate {
	if s != nil {
		pc.SetOffseterAddress(*s)
	}
	return pc
}

// AddTokenIDs adds the "tokens" edge to the CustomerTokens entity by IDs.
func (pc *ProjectCreate) AddTokenIDs(ids ...int) *ProjectCreate {
	pc.mutation.AddTokenIDs(ids...)
	return pc
}

// AddTokens adds the "tokens" edges to the CustomerTokens entity.
func (pc *ProjectCreate) AddTokens(c ...*CustomerTokens) *ProjectCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return pc.AddTokenIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (pc *ProjectCreate) Mutation() *ProjectMutation {
	return pc.mutation
}

// Save creates the Project in the database.
func (pc *ProjectCreate) Save(ctx context.Context) (*Project, error) {
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *ProjectCreate) SaveX(ctx context.Context) *Project {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *ProjectCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *ProjectCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *ProjectCreate) check() error {
	if _, ok := pc.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "Project.address"`)}
	}
	if _, ok := pc.mutation.Slot(); !ok {
		return &ValidationError{Name: "slot", err: errors.New(`ent: missing required field "Project.slot"`)}
	}
	if _, ok := pc.mutation.MinterAddress(); !ok {
		return &ValidationError{Name: "minter_address", err: errors.New(`ent: missing required field "Project.minter_address"`)}
	}
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Project.name"`)}
	}
	if _, ok := pc.mutation.Abi(); !ok {
		return &ValidationError{Name: "abi", err: errors.New(`ent: missing required field "Project.abi"`)}
	}
	if _, ok := pc.mutation.Image(); !ok {
		return &ValidationError{Name: "image", err: errors.New(`ent: missing required field "Project.image"`)}
	}
	return nil
}

func (pc *ProjectCreate) sqlSave(ctx context.Context) (*Project, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *ProjectCreate) createSpec() (*Project, *sqlgraph.CreateSpec) {
	var (
		_node = &Project{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(project.Table, sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt))
	)
	if value, ok := pc.mutation.Address(); ok {
		_spec.SetField(project.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := pc.mutation.Slot(); ok {
		_spec.SetField(project.FieldSlot, field.TypeInt, value)
		_node.Slot = value
	}
	if value, ok := pc.mutation.MinterAddress(); ok {
		_spec.SetField(project.FieldMinterAddress, field.TypeString, value)
		_node.MinterAddress = value
	}
	if value, ok := pc.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pc.mutation.Abi(); ok {
		_spec.SetField(project.FieldAbi, field.TypeJSON, value)
		_node.Abi = value
	}
	if value, ok := pc.mutation.Image(); ok {
		_spec.SetField(project.FieldImage, field.TypeString, value)
		_node.Image = value
	}
	if value, ok := pc.mutation.YielderAddress(); ok {
		_spec.SetField(project.FieldYielderAddress, field.TypeString, value)
		_node.YielderAddress = value
	}
	if value, ok := pc.mutation.OffseterAddress(); ok {
		_spec.SetField(project.FieldOffseterAddress, field.TypeString, value)
		_node.OffseterAddress = value
	}
	if nodes := pc.mutation.TokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TokensTable,
			Columns: project.TokensPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customertokens.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProjectCreateBulk is the builder for creating many Project entities in bulk.
type ProjectCreateBulk struct {
	config
	err      error
	builders []*ProjectCreate
}

// Save creates the Project entities in the database.
func (pcb *ProjectCreateBulk) Save(ctx context.Context) ([]*Project, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Project, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *ProjectCreateBulk) SaveX(ctx context.Context) []*Project {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *ProjectCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *ProjectCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
