-- Create "customer_tokens" table
CREATE TABLE "customer_tokens" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "address" character varying NOT NULL, "slot" bigint NOT NULL, "token_id" character varying NOT NULL, "value" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "customertokens_token_id_slot" to table: "customer_tokens"
CREATE UNIQUE INDEX "customertokens_token_id_slot" ON "customer_tokens" ("token_id", "slot");
-- Create "projects" table
CREATE TABLE "projects" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "address" character varying NOT NULL, "slot" bigint NOT NULL, "minter_address" character varying NOT NULL, "name" character varying NOT NULL, "abi" jsonb NOT NULL, "image" text NOT NULL, "yielder_address" character varying NULL, "offseter_address" character varying NULL, PRIMARY KEY ("id"));
-- Create index "project_address_slot" to table: "projects"
CREATE UNIQUE INDEX "project_address_slot" ON "projects" ("address", "slot");
-- Create "project_tokens" table
CREATE TABLE "project_tokens" ("project_id" bigint NOT NULL, "customer_tokens_id" bigint NOT NULL, PRIMARY KEY ("project_id", "customer_tokens_id"), CONSTRAINT "project_tokens_customer_tokens_id" FOREIGN KEY ("customer_tokens_id") REFERENCES "customer_tokens" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "project_tokens_project_id" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
