// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CustomerTokens is the predicate function for customertokens builders.
type CustomerTokens func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)
